### ISSUE TITLE
duplicate box_id

### ISSUE THREAD

**Issue by meghalithic** [meghalithic/magnifica#14]
There are 19 images with the same box id. We may want to rethink how we label the zooids.

**Comment by agporto** [comment]
You can always merge the image ID with the box ID. That way,  labels would be unique. The box ID was planned as an identifier for a single image.  The idea was to allow us to track down the position of a zooid ( rather than using numerical 1, 2, 3 , etc). It wasn't meant as a global id. Just my two cents,  obviously.  Let me know if you want me to change anything within  Steginator

**Comment by meghalithic** [comment]
Thanks @agporto that resolved the issue!
